export const GET_COMBO_TITLE = "GET_COMBO_TITLE";
export const GET_COMBO_TITLE_SUCCEEDED = "GET_COMBO_TITLE_SUCCEEDED";

export const GET_COMBO_GENDER = "GET_COMBO_GENDER";
export const GET_COMBO_GENDER_SUCCEEDED = "GET_COMBO_GENDER_SUCCEEDED";

export const GET_COMBO_DEPARTMENT = "GET_COMBO_DEPARTMENT";
export const GET_COMBO_DEPARTMENT_SUCCEEDED = "GET_COMBO_DEPARTMENT_SUCCEEDED";
