import { createRequestTypes } from "../commons/actions";

export const GET_PROMOTIONS = "GET_PROMOTIONS";
export const FIND_PROMOTIONS = "FIND_PROMOTIONS";
export const APPLY_PROMOTIONS = "APPLY_PROMOTIONS";
export const GET_PROMOTION_HEADER = "GET_PROMOTION_HEADER";
export const GET_PROMOTION_DETAILS = "GET_PROMOTION_DETAILS";
export const GET_PROMOTION_DETAIL = "GET_PROMOTION_DETAIL";
export const FIND_AND_APPLY_PROMOTIONS = "FIND_AND_APPLY_PROMOTIONS";
export const FIND_PROMOTIONS_REQUEST_TYPE = createRequestTypes(FIND_PROMOTIONS);
export const GET_PROMOTIONS_REQUEST_TYPE = createRequestTypes(GET_PROMOTIONS);
export const APPLY_PROMOTIONS_REQUEST_TYPE = createRequestTypes(APPLY_PROMOTIONS);
export const FIND_AND_APPLY_PROMOTIONS_REQUEST_TYPE = createRequestTypes(FIND_AND_APPLY_PROMOTIONS);
export const GET_PROMOTION_HEADER_REQUEST_TYPE = createRequestTypes(GET_PROMOTION_HEADER);
export const GET_PROMOTION_DETAILS_REQUEST_TYPE = createRequestTypes(GET_PROMOTION_DETAILS);
export const GET_PROMOTION_DETAIL_REQUEST_TYPE = createRequestTypes(GET_PROMOTION_DETAIL);
