export const GET_PROMOTIONS = "GET_PROMOTIONS";
export const GET_PROMOTION = "GET_PROMOTION";
export const ADD_PROMOTION = "ADD_PROMOTION";
export const UPDATE_PROMOTION = "UPDATE_PROMOTION";
export const DELETE_PROMOTION = "DELETE_PROMOTION";

export const PROMOTION_OF = "PROMOTION_OF";
